services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend-only
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app/client
      - ./vite.config.ts:/app/vite.config.ts
      - ./tailwind.config.ts:/app/tailwind.config.ts
      - ./postcss.config.js:/app/postcss.config.js
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true